# Generated by Django 4.2 on 2023-04-25 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(default=9.9)),
                ('catalog', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Shopping_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=9.9)),
                ('quantity', models.IntegerField(default=1)),
                ('customer_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('addrX', models.CharField(max_length=10, null=True)),
                ('addrY', models.CharField(max_length=10, null=True)),
                ('upsID', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_x', models.IntegerField(blank=True, default=-1)),
                ('loc_y', models.IntegerField(blank=True, default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('pack_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('addr_x', models.IntegerField()),
                ('addr_y', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
                ('status', models.CharField(choices=[('packing', 'Packing'), ('packed', 'Packed'), ('loading', 'Loading'), ('loaded', 'Loaded'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='packing', max_length=50)),
                ('amount', models.IntegerField()),
                ('ups_id', models.IntegerField(default=1)),
                ('itemid', models.IntegerField(default=-1)),
                ('truck_id', models.IntegerField(default=-1)),
                ('wh_id', models.IntegerField(default=1)),
                ('price', models.FloatField(max_length=1000)),
                ('version', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.item')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.IntegerField()),
                ('wh_id', models.IntegerField()),
                ('version', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.item')),
            ],
            options={
                'db_table': 'inventory',
                'unique_together': {('item', 'wh_id')},
            },
        ),
    ]
