# Generated by Django 4.2 on 2023-04-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='catalog',
        ),
        migrations.AddField(
            model_name='item',
            name='cataLog',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('food', 'Food'), ('drink', 'Drink'), ('daily_supply', 'Daily Supply'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
