# Generated by Django 4.1.5 on 2023-04-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
