# Generated by Django 4.2 on 2023-04-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_alter_inventory_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('content', models.TextField()),
                ('user_name', models.CharField(max_length=50)),
                ('create_time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
